### ISSUE TITLE
The Latest tag on DockerHub is an out of date Enclave version 

### ISSUE THREAD

**Issue by enclave-marc-barry** [enclave-networks/container.enclave#1]
The latest GA is `2021.12.06.838` but the build on docker hub seems to be `2021.11.02.808`

## Steps to reproduce

```
$ sudo docker pull enclavenetworks/enclave
	latest: Pulling from enclavenetworks/enclave
	Digest: sha256:5989d54773256c3a91811fad04d8e077c8b9c8fdf23c21e1da89c47e3e9dcbe9
$ sudo docker run -it --rm -t enclavenetworks/enclave:latest version
	enclave-linux-x64 2021.11.02.808
```

## What I know so far

- [x] `https://github.com/enclave-networks/docker/blob/main/Dockerfile` attempts to download the latest version of Enclave while the Dockerfile is built by checking `install.enclave.io`. The latest GA version of Enclave is `2021.12.06.838` and the `curl` | `jq` command continues to work as expected. So that's okay.
- [x] I've manually downloaded `https://release.enclave.io/enclave_linux-x64-stable-2021.12.06.838.tar.gz` and run `version` against it, which gives me `enclave-linux-x64 2021.12.06.838`. So that's okay.
- [x] I've forced a rebuild of the Dockerhub image today by manually kicking off a rebuild - https://hub.docker.com/layers/enclavenetworks/enclave/latest/images/sha256-5989d54773256c3a91811fad04d8e077c8b9c8fdf23c21e1da89c47e3e9dcbe9?context=repo&tab=layers
- [x] The SHA256 hashes match between `enclavenetworks/enclave:latest` and what `docker pull` retrieves, `sudo docker inspect --format='{{index .RepoDigests 0}}' enclavenetworks/enclave:latest` produces the hash `5989d54773256c3a91811fad04d8e077c8b9c8fdf23c21e1da89c47e3e9dcbe9` which matches Dockerhub

.... so, what?

## Hypothesis

- Could it be that the docker image is being rebuilt before the manifest file is updated?
- Manually rebuilding the docker image today didn't change the sha256 hash, I would have expected it to because the manifest file is definitely listing the latest version of Enclave.

**Comment by enclave-marc-barry** [comment]
I'm prioritising this issue as fundamental bug fixes are presently unavailable to docker containers

**Comment by enclave-alistair** [comment]
This was caused by dockerhub turning on caching of build layers by default; so an old layer containing the wrong Enclave version was being used incorrectly. 

I've disabled the build caching and re-run, new docker container looks good:

```
alistair@DESKTOP-PTJI1KB:~$ docker pull enclavenetworks/enclave:latest
latest: Pulling from enclavenetworks/enclave
7b1a6ab2e44d: Already exists
9b138f2281b6: Pull complete
9ab4f4661bdd: Pull complete
4f4fb700ef54: Pull complete
d03ec025e155: Pull complete
26aea44e68c9: Pull complete
Digest: sha256:eea0920adbcd8bf2a2ffb96b85f758a05fb71e88e7f31271a63ef7be514e4402
Status: Downloaded newer image for enclavenetworks/enclave:latest
docker.io/enclavenetworks/enclave:latest
alistair@DESKTOP-PTJI1KB:~$ docker run -i --rm enclavenetworks/enclave:latest --version
enclave-linux-x64 2021.12.06.838
alistair@DESKTOP-PTJI1KB:~$
```

**Comment by enclave-marc-barry** [comment]
Magic, thanks Alistair.
